import type { Metadata } from "next";
import "./globals.css";

import localFont from 'next/font/local'
import Gnb from "~/app/components/gnb";

const NanumSquare = localFont({ src: [{path: 'fonts/NanumSquareR.ttf', weight: '400'}] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NanumSquare.className} w-full`}>
        <Gnb />
        <div className='w-screen flex justify-center'>
          <div className='pc:w-[800x] tablet:w-[600px] mobile:w-[380px] pt-6'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
